export const frenchArt = [
  {
    img: "/pictures/france/amurHaunt.jpg",
    author: "Марсель Руссо",
    title: "Охота Амура",
    info: "Холст, масло (50х80)",
    price: "14 500руб",
    shopButton: "В корзину",
  },
  {
    img: "/pictures/france/ladyWithDog.jpg",
    author: "Анри Селин",
    title: "Дама с собачкой",
    info: "Акрил, бумага (50х80)",
    price: "16 500руб",
    shopButton: "В корзину",
  },
  {
    img: "/pictures/france/Proccedures.jpg",
    author: "Франсуа Дюпон",
    title: "Процедура",
    info: "Цветная литография (40х60)",
    price: "20 000руб",
    shopButton: "В корзину",
  },
  {
    img: "/pictures/france/Rose.jpg",
    author: "Луи  Детуш",
    title: "Роза",
    info: "Бумага, акрил (50х80)",
    price: "12 000руб",
    shopButton: "В корзину",
  },
  {
    img: "/pictures/france/birds.jpg",
    author: "Франсуа Дюпон",
    title: "Птичья трапеза",
    info: "Цветная  литография (40х60)",
    price: "22 500руб",
    shopButton: "В корзину",
  },
  {
    img: "/pictures/france/fish.jpg",
    author: "Пьер Моранж",
    title: "Пейзаж с рыбой",
    info: "Цветная литография (40х60)",
    price: "20 000руб",
    shopButton: "В корзину",
  },
];
